workflow_id: workflow_a3c73069
name: New Data Product
summary: This workflow sets up a new Data Product on top of the Base Landing Zone.
overview: This workflow guides you through setting up a new Data Product in Snowflake,
  which includes the necessary databases, schemas, compute warehouses, and Role-Based
  Access Control (RBAC) for proper governance and security.
is_repeatable: true
steps:
- step_4d66d073
- step_bba42d81
- step_55741b57
- step_c8e35425
- step_d019f588
- step_5e280dff
